# Generated by Django 3.2.12 on 2022-02-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0002_auto_20220227_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='density',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='fips',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='run',
            name='popsize',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
    ]
