# Generated by Django 3.2.12 on 2022-03-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0003_auto_20220227_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='configpath',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='run',
            name='logpath',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='run',
            name='videopath',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
